### ISSUE TITLE
Where is 0°?

### ISSUE THREAD

**Issue by gbowman85** [Bitslo/CableGuardian#2]
Is it possible to define where the centre is? It was in the place I wanted it for a long time but now it's somewhere around 100-120° to my right. I always like to face the same direction when I play so I like that the sound beeps when I'm back there. 
If it's not possible to set the position, how is it determined?
Thanks

**Comment by naqaden** [comment]
Same here. It seems to have its own idea about where Front (0°) is, not based on the headset's starting position  nor on SteamVR's front.

I'm using the free version. For me, Cable Guardian thinks "Front" is about 45° to the left of the true front. This offset persists after restarting the app, headset, SteamVR, or PC. Recentering SteamVR 45° to the right doesn't help either.

Unfortunately:
> Note that the neutral orientation (no twist) is always set to 0 degrees (facing forward) regardless of the headset orientation when applying this reset operation.

In other words, reset counter doesn't reset CG's front.

After some digging I found CGConfig.xml stores LastYawValue in radians. So I enabled "Remember turn count," closed CG, changed LastHalfTurn and LastYawValue to 0, oriented my headset torward the true front, and launched CG. Unfortunately again, no change. CG seems to ignore this value and insist that the corner of my room is the front every time it starts up.

As the app is limited to 180° intervals (half-turns) instead of degrees or radians, there is nothing I can do in a custom profile to compensate for a 45° offset.

I'm out of ideas and will cross my fingers for a fix.

**Comment by Bitslo** [comment]
Hi, sorry for the late reply. I hadn't even noticed the original issue since I rarely come here. People seem to post support cases in Steam Discussions, which also contributed to me forgetting about GitHub. I now set up email-notifications so that I wouldn't miss these in the future. 

The front is determined during the SteamVR/Oculus **room setup**. There is no "Cable Guardian front" it just follows the coordinates provided by the API. 

At one point I remember noticing that SteamVR changed something in their handling of the room center. It no longer defaults to the fixed room values - but seems to remember the last user reset. (_Note that the SteamVR reset does not re-calibrate the room_.) However, Cable Guardian always uses the room coordinates, since the idea is to track the physical room (e.g., position markers in the Pro version).

### Solution: Redo the room setup and make sure to point the controller to the front that you want. 
Sorry for the inconvenience, but this is how it works. Let me know if you are still having issues.

(p.s. Note to Pro-version users who might come here: Just remembered that the Pro version has an advanced (slightly experimental) feature called "_Custom origin_" that you _can_ actually use to create a "Cable Guardian front" (kinda contradicting myself here :D ). The feature was not created for this purpose, but I think you could try that as a workaround if you don't want to redo the room setup - but I still recommend that you do!)

**Comment by naqaden** [comment]
Thanks very much for the response, though it leaves me puzzled.

After a SteamVR room setup, a rectangular play-area is fitted to the boundaries. One of the sides of this rectangle is the true front. Cable Guardian is suggesting a corner of this rectangle is the front.

My SteamVR loads one of the default backgrounds (not SteamVR Home) with an arrow on the floor, pointing to the true front. Turn Signal's petals align to the true front. Games that don't respect the headset's starting position align to the true front. Cable Guardian is the only app I have encountered that thinks the front is 45° away.

Doing anything differently during room setup to compensate for this offset would not be ideal. Is there anything I can look up, edit, or provide from my SteamVR files to test the issue?

**Comment by Bitslo** [comment]
Wait, you're right. I was testing with the Pro-version (which works correctly), and I assumed that the free version has the same code for tracking initialization. Turns out, the free version is missing the function that translates the SteamVR calibrated zero to room coordinates - resulting in the behavior you describe. 

I must have thought that I don't need to include the coordinate translation in the free version (_less code = less chance for bugs._) since it only tracks rotation - forgetting about the forward direction syncing.  While it's not essential for operation, it would still be nice to match the orientation of the room setup - I agree.

I'll see if I can cook up a fix for this in the near future (busy now).

**Comment by naqaden** [comment]
I really appreciate you checking again! And for enabling GitHub email-alerts btw, haha.

**Comment by Bitslo** [comment]
Fixed in latest release (1.3.4.2).
